# Generated by Django 4.1 on 2022-08-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('type', models.CharField(max_length=256, verbose_name='Type')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/%Y-%M-%d/')),
            ],
            options={
                'verbose_name_plural': 'Picture Detail',
            },
        ),
    ]
